# Generated by Django 4.2.3 on 2023-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('situacaoentidade', models.IntegerField()),
                ('contato_id', models.IntegerField()),
                ('bateponto', models.BooleanField()),
                ('cargahoraria', models.TimeField(default='00:00:00')),
                ('departamento', models.IntegerField(default=0)),
                ('semintervaloalmoco', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('username',),
            },
        ),
    ]
