# Generated by Django 4.2.3 on 2023-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('primeiro', models.BooleanField(default=False)),
                ('segundo', models.BooleanField(default=False)),
                ('atraso', models.BooleanField(default=False)),
                ('saida', models.DateTimeField()),
                ('usuario_id', models.IntegerField()),
                ('fechado', models.BooleanField(default=False)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('tiporeceita_id', models.IntegerField(blank=True, null=True)),
                ('atrasoautorizado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('entrada',),
            },
        ),
    ]
