# Generated by Django 4.2.3 on 2023-10-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
