# Generated by Django 4.2.3 on 2023-10-04 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apontamento', '0002_alter_ponto_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='ponto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
